### ISSUE TITLE
Shake event on iOS simulator

### ISSUE THREAD

**Issue by ethan-drivr** [deven98/shake#20]
I'm using ShakeDetector with default options and it works perfectly on my iPhone. It doesn't seem to detect "shakes" on the iOS simulator (Simulator menu: Device/Shake.) It there anything I can do to make this work?

**Comment by vladRudenua23** [comment]
any updates ?

**Comment by Codeaview** [comment]
Hello, I am encountering the same issue. The shakes are not detected on the iOS simulator (Simulator menu: Device/Shake)

**Comment by frankpape** [comment]
I was running into this too, and took a look at sensors_plus, which is used by this package. There's nothing in its documentation for `AccelerometerEvent` that suggests it shouldn't work with the simulator, but I came across [this](https://github.com/fluttercommunity/plus_plugins/blob/2aa9f7e0c7b471dc581d6fbd334633d16eb2da03/packages/sensors_plus/sensors_plus/example/integration_test/sensors_plus_test.dart#L13):

`// NOTE: The accelerometer events are not returned on iOS simulators.`

I'm guessing that this issue is unlikely to be resolved as long as `sensors_plus` doesn't support getting the event from the simulator.

**Comment by ervindobri** [comment]
As @frankpape  said it's because accelerometer methods are unimplemented.

My error log hint to the same thing:
```
═══════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel dev.fluttercommunity.plus/sensors/accelerometer:
MissingPluginException(No implementation found for method listen on channel dev.fluttercommunity.plus/sensors/accelerometer)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
platform_channel.dart:368
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:715:11)
platform_channel.dart:715
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
[sentry] [info] Duplicated exception detected. Event 2cc644be634744bab52cb632a81db48c will be discarded.
[sentry] [debug] Event was dropped by a processor
[Talker] ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────
         │ [error] | 12:33:06 732ms | MissingPluginException(No implementation found for method listen on channel dev.fluttercommunity.plus/sensors/accelerometer)
         │ MissingPluginException(No implementation found for method listen on channel dev.fluttercommunity.plus/sensors/accelerometer)
         │ StackTrace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
         │ <asynchronous suspension>
         │ #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:715:11)
         │ <asynchronous suspension>
         │ }
         └──────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
